apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "axumkit-worker.fullname" . }}
  labels:
    {{ include "axumkit-worker.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
