apiVersion: v2
name: axumkit-worker
description: AxumKit Background Worker
type: application
version: 0.4.0
appVersion: "0.4.0"
keywords:
  - axum
  - worker
  - rust
home: https://github.com/levish0/AxumKit
maintainers:
  - name: Levi Laine
